---
title: "Untitled"
author: ""
date: "2024-10-26"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(stringr)
```


```{r}
df <- read.csv("https://raw.githubusercontent.com/Andreina-A/Project-3/refs/heads/main/Data_merged.csv")
head(df)
```


```{r}
df1 <- data.frame(str_split_fixed(df$job_skills, ",", 150))
head(df1)
```


```{r}
df2 <- cbind(df$job_link, df$job_title, df1)
names(df2)[names(df2) == "df$job_link"] <- "job_link"
names(df2)[names(df2) == "df$job_title"] <- "job_title"
head(df2)
```


```{r}
final_df <- pivot_longer(df2, cols = starts_with("X"), names_to = "number", values_to = "skill")
final_df[final_df == ""] <- NA
final_df <- subset(final_df,!is.na(skill))
```


```{r}
occurrences <- final_df %>% count(skill)
occurrences %>% arrange(desc(n))
```

```{r}
df_occur <- occurrences %>% arrange(desc(n))
```

```{r}
program_lang <- c("sql", "java", "python","r", "spark", "c + +", "pandas", "sas", "c++", "c/c++")

data_tools <- c("azure", "excel", "oracle", "mysql","linux", "microsoft office")

job_skill <- c("teamwork","project management" ,"problem solving" , "collaboration", "communication", "problemSolving" ,"attention to detail", "leadership", " Interpersonal Skills", "time management", "team management")
               
data_skill <- c("data Analysis, machine learning", "data visualization", "statistics" , "data warehousing" , "data modeling", "data management", "business intelligence" , "data governance",  "big data", "data security","data science" , "deep learning" , "Data Pipelines","analytical skills", "troubleshooting" , "data integration", "data engineering" ," data security", "cloud computing"," data accuracy", "data transformation", "computer engineering" ,"computer science")
  
data_visual <- c("power bi", "tableau")

```

Filter separate dataset

```{r}
pro_lang_df <- df_occur[df_occur$skill %in% program_lang, ignore.case = TRUE ]

data_tool_df <- df_occur[df_occur$skill %in% data_tools, ignore.case = TRUE ]

job_skill_df <- df_occur[df_occur$skill %in% job_skill, ignore.case = TRUE ]

data_skill_df <- df_occur[df_occur$skill %in% data_skill, ignore.case = TRUE ]

data_visual_df<- df_occur[df_occur$skill %in% data_visual, ignore.case = TRUE ]


```


```{r}
#Programming Language ggplot
ggplot(pro_lang_df, aes(x=skill, y=n)) + 
  geom_bar(stat = "identity", fill="Lightblue") +
     theme(axis.text.x = element_text(angle=60, hjust=1)) +
  ggtitle("Most Valued Data Science Skills (Programming Languages)") +
   ylab("Frequency from Job Postings") + xlab("Programming Language")

#Data tools ggplot
ggplot(data_tool_df, aes(x=skill, y=n)) + 
  geom_bar(stat = "identity", fill="red") +
     theme(axis.text.x = element_text(angle=60, hjust=1)) +
  ggtitle("Most Valued Data Science Skills (Data tools)") +
   ylab("Frequency from Job Postings") + xlab("Data Tools")

#Job Skill ggplot
ggplot(pro_lang_df, aes(x=skill, y=n)) + 
  geom_bar(stat = "identity", fill="green") +
     theme(axis.text.x = element_text(angle=60, hjust=1)) +
  ggtitle("Most Valued Data Science Skills (Job Skill)") +
   ylab("Frequency from Job Postings") + xlab("Job Skills")

#Data Skill ggplot
ggplot(data_skill_df, aes(x=skill, y=n)) + 
  geom_bar(stat = "identity", fill="purple") +
     theme(axis.text.x = element_text(angle=60, hjust=1)) +
  ggtitle("Most Valued Data Science Skills (Data Skill)") +
   ylab("Frequency from Job Postings") + xlab("Data Skills")

#Data Visualization ggplot
ggplot(data_visual_df, aes(x=skill, y=n)) + 
  geom_bar(stat = "identity", fill="pink") +
     theme(axis.text.x = element_text(angle=60, hjust=1)) +
  ggtitle("Most Valued Data Science Skills (Data Visualization)") +
   ylab("Frequency from Job Postings") + xlab("Data Visualization Tools")
```

